language: python

python:
    - "3.6"

before_install:
    - apt-get install zsh
    - pip install setuptools_rust benchmarker
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    - rustup default nightly

install:
    - make install-pip-verbose

script:
    - make test-verbose

after_success:
    - make benchmark
