language: python

python:
    - "3.6"

before_install:
    - pip install setuptools_rust benchmarker
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - rustup default nightly
    - export PATH="$PATH:$HOME/.cargo/bin"

install:
    - make install

script:
    - make test

after_success:
    - make benchmark
