[package]
name = "fpath"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[lib]
name = "path"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.0"
memchr = "2.0"
users = "0.6.1"

[dependencies.pyo3]
version = "0.2"
features = ["extension-module"]
